development:
  host: localhost
  database: dragon_hoard_development

test:
  host: localhost
  database: dragon_hoard_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>

